name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v2

      - name: Install NPM dependencies ğŸ“¦
        uses: bahmutov/npm-install@v1

      - name: Tests ğŸ§ª
        run: npm test

      - name: Run update ğŸ“Š
        run: bin/update-badge.js prettier

      - name: Update badges demo ğŸ·
        run: npm run demo

      - name: Short badges demo ğŸ·
        run: npm run demo:short

      - name: Behind latest version badges demo ğŸ·
        run: npm run demo:behind

      - name: Multiple --from demo ğŸ·
        run: npm run demo:from

      - name: Semantic Release ğŸš€
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
